name: Publish Container Image to GHCR.IO

on:
  push:
  pull_request:
    types: [closed]
  release:
    types: [created]

jobs:
  build_container_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@main
